onlinequiz1/myapp/urls.py
from django.conf.urls import url
from myapp import views
app_name ='quiz'
urlpatterns = [
    url('question/',views.quiz, name='question'),
    #url('result/',views.result, name='result'),
    url('quiz/',views.facts, name='facts'),

]

onlinequiz1/onlinequiz/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index' ),
    path('quiz/',include('myapp.urls'))
]

onlinequiz1/myapp/models.py
from django.db import models

# Create your models here.
class feedback(models.Model):
    name= models.CharField(max_length=200)
    email= models.EmailField(max_length=250)
    message = models.TextField()
    Date = models.DateTimeField(auto_now_add=True, blank = True)


    def __str__(self):
        return self.message

    class Meta:
        verbose_name_plural = 'Feedback'

class scoreboard(models.Model):
    Right_Answers= models.CharField(max_length=200)
    Wrong_Answers= models.CharField(max_length=250)
    Date = models.DateTimeField(auto_now_add=True, blank = True)

    def __str__(self):
        return repr(self.Date)

    class Meta:
        verbose_name_plural = 'Score Board'

onlinequiz1/myapp/views.py
from django.shortcuts import render
from myapp.models import feedback, scoreboard
from django.http import HttpResponse
import requests
# Create your views here.
def index(request):
    if request.method =='POST':
        name = request.POST['name']
        email=request.POST['email']
        message=request.POST['message']


        feedbackobj = feedback(name=name,email=email,message=message)

        feedbackobj.save()
        print('data saved')

    return render(request, 'index.html')

def quiz(request):
    api = requests.get('http://sachtechsolution.com/dailydose/admin/webservice/questionsProcess.php?type=questions')
    mydata= api.json()
    right = 0
    wrong = 0
    result = {'myans':'active'}
    count = 1
    mynewdata = []
    for q in mydata['Questions']:

        dic = {'id':count,'question':q['question'],'qid':q['ques_id'],'a':q['option1'],'b':q['option2'],'c':q['option3'],'d':q['option4']}
        mynewdata.append(dic)
        count += 1
    #print(mynewdata)
    for a in mydata['Questions']:
        if request.method == 'POST' and request.POST:
            if a['answer'] == request.POST[a['ques_id']]:
                right += 1
            else:
                wrong += 1


    result['right'] = right;
    result['wrong'] = wrong;
    print(result)
    if result['right'] == 0 or result['wrong'] == 0:
        return render(request, 'quiz.html',context = {'quiz':mynewdata})
    else:
        scores = scoreboard(Right_Answers=right, Wrong_Answers=wrong)
        scores.save()
        print('saved successfully')
        board = scoreboard.objects.order_by('Date')


        return render(request, 'result.html',context = {'quiz':result,'des':mydata,'board':board})

def facts(request):
    apfact = requests.get('http://sachtechsolution.com/dailydose/admin/webservice/factProcess.php?type=getLanguageFacts&languageId=3')
    data =apfact.json()
    return render(request,'fact.html',context = {'fact':data['facts']})

onlinequiz1/templates/fact.html
<!DOCTYPE html>
{% load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ONLINE QUIZ</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" >

    <style>
    .transbox {
       margin:5%;
       padding:5%;
       background-color: #ffffff;
       border: 2px solid red;
       opacity: 0.6;
       border-radius: 10px;
 }
 .sq:hover{
   color:black;
 }
    </style>
  </head>
  <body class=""  style='background:rgba(255,0,0,0.2)'>
    <div class="container-fluid px-0">
      <div class="row">
        <div class="col-md-12">
          <nav class='navbar bg-dark navbar-dark navbar-expand-sm'>
            <a href="{% url "index"%}" class='navbar-brand'>Online Quiz</a>
            <ul class='navbar-nav ml-auto'>
              <a href="{% url "quiz:question"%}" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq '> <<< Start Quiz!!!</li>
              </a>
              <a href="{% url "index"%}" class='nav-link btn btn-outline-light'>
                <li class='nav-item sq'> Go to Homepage</li>
              </a>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row" style="background:url('{% static 'images/mystery.jpg'%}');padding:7%;background-size: 100% 100%;  background-attachment:fixed;">
        <div class="col-md-6 mx-auto">
          <h1 class='transbox mx-auto'><i class="fas fa-question mr-2" style='color:red; margin-right:10px;'></i> Did you Know <i class="fas fa-question mr-2" style='color:red; margin-right:10px;'></i><i class="fas fa-question mr-2" style='color:red; margin-right:10px;'></i></h1>

        </div>
      </div>
    </div>
    <div class="container">
      <div class=" col-md-12 bg-light p-5 m-5">
          <table class="table table-striped alert alert-s ">
            <tbody>
          {% for i in fact %}

              <tr>
                <td>{{i.thought}} </td>
              </tr>

          {% endfor %}
          </tbody>
          </table>
      </div>
    </div>
    <div class="container-fluid text-center" style='margin:0px;' id='about'>
      <div class="row">
        <div class="col-md-12" style="padding:3%; background:black; color:white;">
          <strong>Powered By :</strong> <br/> <i class="fa fa-user" style='padding-right:2px;'></i> Shivam Gautam <br/>
          <span class='justify-content-center'>Copyright &copy; <a href="http://www.sachtechsolution.com/" style='color:white;'>Sachtech Solution Pvt. ltd.</a></span>

        </div>
      </div>
    </div>
  </body>
</html>

onlinequiz1/templates/quiz.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}" >
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" >
    <title>QUIZ</title>
    <style>
    div.transbox {
       margin:5%;
       background-color: rgba(255,255,255,.9);
       border: 1px solid red;
       padding:3%;
       border-radius: 10px;
 }
.sq:hover{
  color:black;
}
  </style>
  </head>
  <body style='background:rgba(250,0,0,0.1)'>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 px-0">
          <nav class='navbar bg-dark navbar-dark navbar-expand-sm'>
            <a href="{% url "index"%}" class='navbar-brand'>Online Quiz</a>
            <ul class='navbar-nav ml-auto'>
              <li class="nav-item">
                <a href="{% url "index"%}" class="nav-link">Home</a>
              </li>
              <li class="nav-item">
                <a href="#quiz" class="nav-link">Start Quiz <i class="fas fa-arrow-down ml-2"></i></a>
              </li>

              <!-- <a href="" class='nav-link btn btn-outline-light'>
                <li class='nav-item sq'>Start quiz</li>
              </a> -->
              <!-- <a href="{% url "index"%}" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq '> <<< Home</li>
              </a> -->

            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="container-fluid ">
      <div class="row h-100 justify-content-center py-4" style="font-family:arial;  background-image: url('{% static 'images/quiz.jpeg' %}'); background-size:100% 100%; background-attachment:fixed;">
        <div class="col-md-6 transbox">
          <h2 class=' text-dark text-center'>Are you here</h2><h2 class='pl-5 text-success' style='margin-left:20%;'> with the SOLUTION</h2>
          <h1 class='text-center'>or Are you Part of the<br/> <span  style='font-weight:bold; color:red;'>Problem ???<i class="fas fa-question" style='font-size:50px;'></i></span></h1>
        </div>
      </div>
      <div class="row " id='quiz'>
        <div class="col-md-9 bg-light my-5 py-5" style='margin:0 auto; border:1px solid red; border-radius:10px; '>
          <form method="post" action="">

            {% csrf_token %}
            {% for i in quiz %}
              <div type='1' class='alert alert-danger mt-5'><strong>{{i.id}} . </strong>{{ i.question }}</div>

                <div class='aabb form-control'><input type="radio" value='a' name='{{ i.qid }}' checked />{{ i.a}}</div>
                <div class='aabb form-control'><input type="radio" value='b' name='{{ i.qid }}' />{{ i.b }}</div>
                <div class='aabb form-control'><input type="radio" value='c' name='{{ i.qid }}' />{{ i.c }}</div>
                <div class='aabb form-control'><input type="radio" value='d' name='{{ i.qid }}' />{{ i.d }}</div>
              {% endfor %}
              <br/>
              <input type="submit" class='btn btn-block btn-success py-2 my-4' />
              </div>

          </form>
        </div>
      </div>
    </div>
    <script>
      $(document).ready(function(){
        $('.aabb').click(function(){
          $(this).css("color","orange");
        });
      });
    </script>
    <div class="container-fluid text-center" style='margin:0px;' id='about'>
      <div class="row">
        <div class="col-md-12" style="padding:3%; background:black; color:white;">
          <strong>Powered By :</strong> <br/> <i class="fa fa-user" style='padding-right:2px;'></i> Shivam Gautam <br/>
          <span class='justify-content-center'>Copyright &copy; <a href="http://www.sachtechsolution.com/" style='color:white;'>Sachtech Solution Pvt. ltd.</a></span>

        </div>
      </div>
    </div>

  </body>
</html>

onlinequiz1/templates/result.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <title>ONLINE QUIZ</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css">

    <script>
      function myfun(){
        var x =prompt('Very nice attempt, Please tell me your Name!!!');
        if(x=='' || x==null){
          document.write('<h1>Name required!!!</h1>');
        }
        else{
           document.getElementById("name").innerHTML =x;


      }
    }
    </script>
    <script>
      $(document).ready(function(){
        $('#button').click(function(){
          $('#scoreb').fadeToggle(2000);
        });
      });
    </script>

    <style>
.sq:hover{
  color:black;
}
  </style>
  </head>
  <body onload='myfun()'>
    <div class="container-fluid px-0">
      <div class="row">
        <div class="col-md-12">
          <nav class='navbar bg-dark navbar-dark navbar-expand-sm'>
            <a href="{% url "index"%}" class='navbar-brand'>Online Quiz</a>
            <ul class='navbar-nav ml-auto'>
              <a href="{% url "quiz:question"%}" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq '> << Start Again!!!</li>
              </a>
              <a href="{% url "index"%}" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq '> <<< Home</li>
              </a>
              <a href="#details" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq'> View Answer Description</li>
              </a>
              <a href="#scoreb" id='button' class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq'> View Previous scoreboard</li>
              </a>
              <a href="#" class='nav-link'>
                <li class='nav-item' ><i class="fas fa-use mr-2" style='font-size:20px; color:white;'> <span id='name' name='res' class='nav-item'></span> </i></li>
                <!-- <form class="" name='myform' method="post">
                  {% csrf_token %}
                  {{ myform.as_p }}
                  <input type="text" id='na' name=

                  'na' value=""/>
                </form> -->

              </a>

            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row" style='background:rgba(255,0,0,0.1); background-attachment:fixed;'>
        <div class="container">
          <div class="row my-5">
            <div class="col-md-12">
              <h1 class="text-center alert-success my-5 pb-5" id='name' style='text-shadow:20px 10px 10px black; box-shadow:20px 10px 10px black; border-radius:50%;'>Your Result</h1>
            </div>
            <div class="col-md-6 mx-auto mt-5 p-2 bg-light">
              <div class="bg-success py-5">
                <h1 class="text-center display-1">{{ quiz.right }}</h1>
              </div>
            </div>
            <div class='col-md-6 mx-auto mt-5 p-2 bg-light'>
              <div class="bg-danger py-5">
                <h1 class="text-center display-1">{{ quiz.wrong }}</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid p-5 " id='details' style='background:rgba(0, 255, 0,0.1); background-attachment:fixed; '>
      <div class="row">
        <div class="col-md-9 mx-auto bg-light p-5" style='border-radius:20px;'>
          <h1 class='text-warning text-center p-5 mb-5' style='background:rgba(125,50,125,0.1); text-shadow:20px 10px 10px black; box-shadow:20px 10px 10px black; border-radius:50%;'>Here is Details of Answer</h1>
          <dl class="list-group">

            {% for i in des.Questions %}

              <dd class='alert alert-danger p-2 ' style='font-size:20px'><strong>Question:</strong>{{ i.question }}</dd>
              <dd class='alert alert-success p-3'><strong>Description:</strong>{{ i.explanation }}</dd>
              <dd class='alert alert-success p-3'><strong>Correct Option:</strong> {{ i.answer }}</dd>
            {% endfor %}
          </dl>

        </div>
      </div>
    </div>
    {% if board %}
    <div class="container-fluid my-5" id='scoreb' style='display:none; border-radius:10px;'>
      <div class="row">
        <div class="col-md-12">
          <h1 class='py-5 my-3 text-center text-success'style='background:rgba(255,0,0,0.1)'>Here is previous Score Board</h1>
        </div>
        <div class="col-md-12">
          <table class='table my-5 table-hover'>
            <thead>
              <tr>
                <th>Sr. No</th>
                <th>Correct Answers</th>
                <th>Wrong Answers</th>
                <th>Date</th>
              </tr>
            </thead>
            {% for i in board %}
            <tbody>
              <tr>
                <td> {{i.id}} </td>
                <td>{{ i.Right_Answers }}</td>
                <td>{{ i.Wrong_Answers }}</td>
                <td> {{ i.Date }} </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
    {% endif %}
    <div class="container-fluid text-center" style='margin:0px;' id='about'>
      <div class="row">
        <div class="col-md-12" style="padding:3%; background:black; color:white;">
          <strong>Powered By :</strong> <br/> <i class="fa fa-user" style='padding-right:2px;'></i> Shivam Gautam <br/>
          <span class='justify-content-center'>Copyright &copy; <a href="http://www.sachtechsolution.com/" style='color:white;'>Sachtech Solution Pvt. ltd.</a></span>

        </div>
      </div>
    </div>

  </body>
  <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"> -->
</html>